repos:
  - repo: local
    hooks:
      - id: "pre-commit-package"
        name: "package.json"
        language: "system"
        entry: "pnpm run pkg:check && pnpm run pkg:format"
        pass_filenames: false
        files: package.json$
  - repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 20.8b1 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.1.2"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.1.2
          - typescript@4.3.2
          - prettier-plugin-organize-imports@2.3.4
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v7.32.0"
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - eslint@7.32.0
          - eslint-config-prettier@8.3.0
          - eslint-plugin-prettier@3.4.1
          - eslint-plugin-react@7.24.0
          - eslint-plugin-react-hooks@4.2.0
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
