# This is a basic workflow to help you get started with Actions

name: Docker CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  repository_dispatch:
    types: [manual-trigger]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  buildpush:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    strategy:
      matrix:
        image: [-i orchest-api -i orchest-webserver -i auth-server,
                -i jupyter-server,
                -i orchest-ctl -i custom-base-kernel-py -i custom-base-kernel-r,
                -i nginx-proxy,
                -i celery-worker -i memory-server]
  
    steps:
    - uses: actions/checkout@v2

    - name: Build and push image
      run: |
          bash ./scripts/build_container.sh ${{ matrix.image }} -v
          echo "-----------"
          bash ./scripts/push_container.sh ${{ matrix.image }}
      
  push-readme:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    
    steps:
    - uses: actions/checkout@v2
    - name: Push README files to DockerHub nginx-proxy
      uses: peter-evans/dockerhub-description@v2
      env:
        DOCKERHUB_REPOSITORY: orchestsoftware/nginx-proxy
        README_FILEPATH: orchest/nginx-proxy/README.md

    - name: Push README files to DockerHub celery-worker
      uses: peter-evans/dockerhub-description@v2
      env:
        DOCKERHUB_REPOSITORY: orchestsoftware/celery-worker
        README_FILEPATH: orchest/orchest-api/README.md

    - name: Push README files to DockerHub orchest-ctl
      uses: peter-evans/dockerhub-description@v2
      env:
        DOCKERHUB_REPOSITORY: orchestsoftware/orchest-ctl
        README_FILEPATH: orchest/orchest-ctl/README.md

    - name: Push README files to DockerHub custom-base-kernel-r
      uses: peter-evans/dockerhub-description@v2
      env:
        DOCKERHUB_REPOSITORY: orchestsoftware/custom-base-kernel-r
        README_FILEPATH: orchest/custom-images/custom-base-kernel-r/README.md

    - name: Push README files to DockerHub custom-base-kernel-py
      uses: peter-evans/dockerhub-description@v2
      env:
        DOCKERHUB_REPOSITORY: orchestsoftware/custom-base-kernel-py
        README_FILEPATH: orchest/custom-images/custom-base-kernel-py/README.md

    - name: Push README files to DockerHub orchest-api
      uses: peter-evans/dockerhub-description@v2
      env:
        DOCKERHUB_REPOSITORY: orchestsoftware/orchest-api
        README_FILEPATH: orchest/orchest-api/README.md

    - name: Push README files to DockerHub jupyter-server
      uses: peter-evans/dockerhub-description@v2
      env:
        DOCKERHUB_REPOSITORY: orchestsoftware/jupyter-server
        README_FILEPATH: orchest/jupyter-server/README.md

    - name: Push README files to DockerHub orchest-webserver
      uses: peter-evans/dockerhub-description@v2
      env:
        DOCKERHUB_REPOSITORY: orchestsoftware/orchest-webserver
        README_FILEPATH: orchest/orchest-webserver/README.md

    - name: Push README files to DockerHub memory-server
      uses: peter-evans/dockerhub-description@v2
      env:
        DOCKERHUB_REPOSITORY: orchestsoftware/memory-server
        README_FILEPATH: orchest/memory-server/README.md

    - name: Push README files to DockerHub auth-server
      uses: peter-evans/dockerhub-description@v2
      env:
        DOCKERHUB_REPOSITORY: orchestsoftware/auth-server
        README_FILEPATH: orchest/auth-server/README.md
