# This is a basic workflow to help you get started with Actions

name: Docker CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  repository_dispatch:
    types: [manual-trigger]
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  buildpush:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # RELEASE_TAG: ${{ github.event.client_payload.release_tag }}
      RELEASE_TAG: "latest"

    strategy:
      matrix:
        image:
          [
            -i orchest-api -i orchest-webserver -i auth-server,
            -i jupyter-server,
            -i jupyter-enterprise-gateway,
            -i orchest-ctl -i base-kernel-py -i base-kernel-r,
            -i base-kernel-py-gpu,
            -i nginx-proxy,
            -i update-server,
            -i file-manager,
            -i celery-worker -i memory-server,
          ]

    steps:
      - uses: actions/checkout@v2

      - name: Build and push image
        run: |
          bash ./scripts/pull_container.sh ${{ matrix.image }} -t "$RELEASE_TAG"
          echo "-----------"
          bash ./scripts/build_container.sh ${{ matrix.image }} -v -t "$RELEASE_TAG"
          echo "-----------"
          bash ./scripts/push_container.sh ${{ matrix.image }} -t "$RELEASE_TAG"

  push-readme:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - name: Push README files to DockerHub nginx-proxy
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_REPOSITORY: orchest/nginx-proxy
          README_FILEPATH: services/nginx-proxy/README.md

      - name: Push README files to DockerHub celery-worker
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_REPOSITORY: orchest/celery-worker
          README_FILEPATH: services/orchest-api/README.md

      - name: Push README files to DockerHub orchest-ctl
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_REPOSITORY: orchest/orchest-ctl
          README_FILEPATH: services/orchest-ctl/README.md

      - name: Push README files to DockerHub base-kernel-r
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_REPOSITORY: orchest/base-kernel-r
          README_FILEPATH: services/base-images/base-kernel-r/README.md

      - name: Push README files to DockerHub base-kernel-py
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_REPOSITORY: orchest/base-kernel-py
          README_FILEPATH: services/base-images/base-kernel-py/README.md

      - name: Push README files to DockerHub orchest-api
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_REPOSITORY: orchest/orchest-api
          README_FILEPATH: services/orchest-api/README.md

      - name: Push README files to DockerHub jupyter-server
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_REPOSITORY: orchest/jupyter-server
          README_FILEPATH: services/jupyter-server/README.md

      - name: Push README files to DockerHub jupyter-enterprise-gateway
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_REPOSITORY: orchest/jupyter-enterprise-gateway
          README_FILEPATH: services/jupyter-enterprise-gateway/README.md

      - name: Push README files to DockerHub orchest-webserver
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_REPOSITORY: orchest/orchest-webserver
          README_FILEPATH: services/orchest-webserver/README.md

      - name: Push README files to DockerHub memory-server
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_REPOSITORY: orchest/memory-server
          README_FILEPATH: services/memory-server/README.md

      - name: Push README files to DockerHub auth-server
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_REPOSITORY: orchest/auth-server
          README_FILEPATH: services/auth-server/README.md

      - name: Push README files to DockerHub update-server
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_REPOSITORY: orchest/update-server
          README_FILEPATH: services/update-server/README.md

      - name: Push README files to DockerHub file-manager
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_REPOSITORY: orchest/file-manager
          README_FILEPATH: services/file-manager/README.md
