name: Sync new GitHub issues to Jira

on:
  issues:
    types: [opened]

jobs:
  create-issue:
    steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Create
        id: create
        uses: atlassian/gajira-create@master
        with:
          project: ORCHEST
          issuetype: Improvement
          summary: |
            ${{ github.event.issue.title }}
          description: |
            New issue on GitHub ${{ github.repository }}
