# Runs pre-commit on all changed files.
name: pre-commit

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      # Skip our pnpm pre-commit hook
      SKIP: pnpm-pre-commit

    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      # Run our pnpm hook manually, with additional build checks
      - name: Setup pnpm
        run: npm run setup && pnpm install

      - name: Build pnpm packages
        run: pnpm run build

      - name: Lint pnpm packages
        run: pnpm run lint

      # Continue with pre-commit workflow
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: " "

      - uses: pre-commit/action@v2.0.0
        with:
          extra_args: --files ${{ steps.file_changes.outputs.files }}
