name: Python Tests

on:
  push:
    branches:
      - master
      - dev
      - "release/**"
    paths:
      - "**.py"
      - "**/tests/**"
  pull_request:
    branches:
      - master
      - dev
      - "release/**"

jobs:
  pythontests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          [
            memory-server,
            session-sidecar,
            orchest-api,
            orchest-webserver,
            orchest-sdk,
            base-images-runnable,
            orchest-ctl,
          ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Test with pytest
        run: |
          python -m pip install --upgrade pip
          bash ./scripts/run_tests.sh -s ${{ matrix.service }} --no-venv
